fragment SiteContentParts on SiteContent {
  __typename
  navigation {
    __typename
    brandPrefix
    brandAccent
    links {
      __typename
      label
      href
      hasDropdown
    }
    servicesDropdownLabel
    primaryCta {
      __typename
      href
      label
    }
    mobileTitle
  }
  footer {
    __typename
    description
    quickLinksHeading
    servicesHeading
    contactHeading
    address
    phone
    email
    copyright
    legal
    socials {
      __typename
      type
      href
    }
  }
  home {
    __typename
    hero {
      __typename
      eyebrow
      headingPrefix
      rotatingWords
      headingSuffix
      description
      image
      imageAlt
      primaryCta {
        __typename
        href
        label
      }
      secondaryCta {
        __typename
        href
        label
      }
      insightLabel
      insightItems
    }
    clients {
      __typename
      label
      rowOne
      rowTwo
    }
    whatWeDo {
      __typename
      label
      title
      description
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    servicesPreview {
      __typename
      label
      title
      description
      viewAllLabel
      scrollLabel
      exploreLabel
    }
    whyChoosePr {
      __typename
      label
      title
      description
      image
      imageAlt
      checklist {
        __typename
        number
        text
      }
    }
    whySubscribe {
      __typename
      label
      title
      description
      cards {
        __typename
        id
        icon
        title
        description
      }
    }
    whyChooseUs {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    projectsPreview {
      __typename
      footerText
      primaryCta {
        __typename
        href
        label
      }
      secondaryCta {
        __typename
        href
        label
      }
    }
    testimonialsIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    letsTalk {
      __typename
      eyebrow
      heading
      supporting
      primaryCta {
        __typename
        href
        label
      }
      secondaryCta {
        __typename
        href
        label
      }
    }
    contactShort {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
  }
  pageHeroes {
    __typename
    services {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    caseStudies {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    blog {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    contact {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
  }
  about {
    __typename
    hero {
      __typename
      eyebrow
      headingLineOne
      headingLineTwo
      description
      scrollLabel
    }
    mission {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    stats {
      __typename
      value
      suffix
      label
      detail
      description
    }
    timelineIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    valuesIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    values {
      __typename
      icon
      title
      description
    }
    closing {
      __typename
      eyebrow
      heading
      supporting
      primaryCta {
        __typename
        href
        label
      }
      secondaryCta {
        __typename
        href
        label
      }
    }
  }
  servicesPage {
    __typename
    serviceCtaLabel
    intro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    highlights {
      __typename
      value
      suffix
      label
      detail
      description
    }
    fullList {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    closing {
      __typename
      eyebrow
      heading
      supporting
      primaryCta {
        __typename
        href
        label
      }
      secondaryCta {
        __typename
        href
        label
      }
    }
    detail {
      __typename
      focusLabel
      whyLabel
      startCta {
        __typename
        href
        label
      }
      allServicesCta {
        __typename
        href
        label
      }
      processIntro {
        __typename
        label
        title
        heading
        homeLabel
        currentLabel
        noteLabel
        titlePrefix
        titleAccent
        titleSuffix
        description
        supporting
        note
        quote
        button
        image
        imageAlt
        cta {
          __typename
          href
          label
        }
      }
      relatedIntro {
        __typename
        label
        title
        heading
        homeLabel
        currentLabel
        noteLabel
        titlePrefix
        titleAccent
        titleSuffix
        description
        supporting
        note
        quote
        button
        image
        imageAlt
        cta {
          __typename
          href
          label
        }
      }
      closing {
        __typename
        eyebrow
        heading
        supporting
        primaryCta {
          __typename
          href
          label
        }
        secondaryCta {
          __typename
          href
          label
        }
      }
    }
  }
  blogPage {
    __typename
    intro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    backLabel
    closing {
      __typename
      eyebrow
      primaryCta {
        __typename
        href
        label
      }
    }
  }
  caseStudiesPage {
    __typename
    includedIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    closing {
      __typename
      eyebrow
      heading
      supporting
      primaryCta {
        __typename
        href
        label
      }
      secondaryCta {
        __typename
        href
        label
      }
    }
    detail {
      __typename
      backLabel
      summaryLabel
      blocks
      resultsLabel
      resultsHeading
      closing {
        __typename
        eyebrow
        heading
        supporting
        primaryCta {
          __typename
          href
          label
        }
        secondaryCta {
          __typename
          href
          label
        }
      }
    }
  }
  contactPage {
    __typename
    consultationRequest {
      __typename
      label
      title
      description
      confidentiality
    }
    form {
      __typename
      namePlaceholder
      emailPlaceholder
      phonePlaceholder
      companyPlaceholder
      primarySelectLabel
      primarySelectOptions
      secondarySelectLabel
      secondarySelectOptions
      messagePlaceholder
      submitLabel
    }
    otherOptionsIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    finalCta {
      __typename
      label
      note
    }
  }
  data {
    __typename
    services {
      __typename
      slug
      shortLabel
      title
      eyebrow
      description
      intro
      longDescription
      image
      heroImage
      keywords
      subServices
      process {
        __typename
        title
        description
      }
      metrics {
        __typename
        value
        suffix
        label
        detail
        description
      }
    }
    serviceTickerTags
    allServiceGroups {
      __typename
      title
      items
    }
    projectCategories
    projectSectionIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    projectsPageIntro {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    projectsClosingCta {
      __typename
      label
      title
      heading
      homeLabel
      currentLabel
      noteLabel
      titlePrefix
      titleAccent
      titleSuffix
      description
      supporting
      note
      quote
      button
      image
      imageAlt
      cta {
        __typename
        href
        label
      }
    }
    projectItems {
      __typename
      id
      slug
      title
      category
      market
      duration
      teaserOutcome
      summary
      outcomes
    }
    homepageFeaturedProjectSlugs
    portfolioItems {
      __typename
      id
      slug
      category
      client
      title
      result
      excerpt
      image
      market
      engagementDuration
      situation
      strategy
      execution
      results {
        __typename
        value
        suffix
        label
        detail
        description
      }
      metrics {
        __typename
        value
        suffix
        label
        detail
        description
      }
    }
    featuredCaseStudy {
      __typename
      client
      title
      result
      excerpt
      image
    }
    blogPosts {
      __typename
      slug
      category
      title
      excerpt
      image
      readTime
      content
    }
    contact {
      __typename
      contactPageIntro {
        __typename
        label
        title
        heading
        homeLabel
        currentLabel
        noteLabel
        titlePrefix
        titleAccent
        titleSuffix
        description
        supporting
        note
        quote
        button
        image
        imageAlt
        cta {
          __typename
          href
          label
        }
      }
      contactStrategyConsultation {
        __typename
        label
        title
        paragraphs
        highlights {
          __typename
          title
          description
        }
      }
      contactOptions {
        __typename
        label
        title
        description
        value
        href
        external
      }
      contactExpectationsIntro {
        __typename
        label
        title
        heading
        homeLabel
        currentLabel
        noteLabel
        titlePrefix
        titleAccent
        titleSuffix
        description
        supporting
        note
        quote
        button
        image
        imageAlt
        cta {
          __typename
          href
          label
        }
      }
      contactExpectations {
        __typename
        title
        timeframe
        description
      }
      contactConversationTopicsIntro {
        __typename
        label
        title
        heading
        homeLabel
        currentLabel
        noteLabel
        titlePrefix
        titleAccent
        titleSuffix
        description
        supporting
        note
        quote
        button
        image
        imageAlt
        cta {
          __typename
          href
          label
        }
      }
      contactConversationTopics {
        __typename
        title
        description
      }
      contactFaqs {
        __typename
        question
        answer
      }
      contactReasonsIntro {
        __typename
        label
        title
        heading
        homeLabel
        currentLabel
        noteLabel
        titlePrefix
        titleAccent
        titleSuffix
        description
        supporting
        note
        quote
        button
        image
        imageAlt
        cta {
          __typename
          href
          label
        }
      }
      contactReasons {
        __typename
        title
        description
      }
    }
    heroStats {
      __typename
      value
      suffix
      label
      detail
      description
    }
    statsTicker {
      __typename
      value
      suffix
      label
      detail
      description
    }
    performanceStats {
      __typename
      value
      suffix
      label
      detail
      description
    }
    testimonials {
      __typename
      name
      role
      quote
    }
    timeline {
      __typename
      year
      title
      description
    }
    teamMembers {
      __typename
      name
      role
      image
      linkedin
    }
  }
}
